# @CommandService_HostAddress = http://localhost:5201
@CommandService_HostAddress = http://myacme.com

# http://myacme.com/api/platforms


GET {{CommandService_HostAddress}}/weatherforecast
Accept: application/json


###

POST {{CommandService_HostAddress}}/api/c/platforms
Accept: application/json

###