@CommandService_HostAddress = http://localhost:5201
# @CommandService_HostAddress = http://myacme.com

# http://myacme.com/api/platforms


GET {{CommandService_HostAddress}}/weatherforecast
Accept: application/json
###

GET {{CommandService_HostAddress}}/api/c/platforms
Accept: application/json
###

GET {{CommandService_HostAddress}}/api/c/platforms/1/commands
Accept: application/json
###

GET {{CommandService_HostAddress}}/api/c/platforms/1/commands/3
Accept: application/json
###

POST {{CommandService_HostAddress}}/api/c/platforms
Accept: application/json

### CREATE A PLATFORM
POST {{CommandService_HostAddress}}/api/c/platforms/1/commands
Content-Type: application/json

{
  "HowTo": "Build a dotnet project",
  "CommandLine": "dotnet build",
}
###