@CommandService_HostAddress = http://localhost:5201

GET {{CommandService_HostAddress}}/weatherforecast/
Accept: application/json

###

POST {{CommandService_HostAddress}}/api/c/platforms
Accept: application/json

###